"""Produce a SPECIMEN review statement over a synthetic package.

    python examples/specimen_statement.py [outfile]

The package built here is invented for demonstration. Nothing in the output
describes any real system, and the statement says so on its own face. The point
is to let a prospective client see the exact shape of the deliverable —
including what a refusal looks like — before committing to anything.
"""

from __future__ import annotations

import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from attest import (  # noqa: E402
    Artifact,
    Claim,
    EvidenceChain,
    digest_file,
    issue_statement,
    render,
    verify_statement,
)

SCOPE = (
    "SPECIMEN over a synthetic demonstration package. Covers artifact integrity "
    "(SHA-256 recomputed from disk), evidence-chain consistency, claim-to-artifact "
    "traceability, and the presence of a reproduction command per claim. Does NOT "
    "cover live execution, broker connectivity, order routing, capital adequacy, or "
    "whether any strategy is profitable. Demo/paper evidence only."
)

BANNER = """\
================================================================================
SPECIMEN - this statement reviews a SYNTHETIC package created solely to show the
shape of the deliverable. It is not a review of any real system, and the digests
below belong to files generated by this script at runtime.
================================================================================
"""


def build(root: Path) -> EvidenceChain:
    (root / "returns_xauusd_demo.csv").write_text(
        "date,ret\n"
        "2026-08-03,0.0041\n2026-08-04,-0.0012\n2026-08-05,0.0007\n"
        "2026-08-06,-0.0033\n2026-08-07,0.0019\n",
        encoding="utf-8",
    )
    (root / "spec.md").write_text(
        "# Candidate specification\n\n"
        "Risk per position is capped at 1% of equity.\n"
        "Positions are closed before the weekend.\n",
        encoding="utf-8",
    )
    (root / "run_log.txt").write_text(
        "2026-08-03T07:00:02Z session open\n2026-08-07T20:59:58Z session close\n",
        encoding="utf-8",
    )

    chain = EvidenceChain()
    for aid, path in (
        ("returns", "returns_xauusd_demo.csv"),
        ("spec", "spec.md"),
        ("runlog", "run_log.txt"),
    ):
        chain.add_artifact(Artifact(aid, path, digest_file(root / path)))

    chain.add_claim(
        Claim(
            "C1",
            "every daily mark in the report exists in returns_xauusd_demo.csv",
            "returns",
            reproduction="python -m tools.trace_marks --evidence returns_xauusd_demo.csv",
            verdict="supported",
        )
    )
    chain.add_claim(
        Claim(
            "C2",
            "no position is held across a weekend boundary",
            "runlog",
            reproduction="python -m tools.weekend_scan --log run_log.txt",
            verdict="supported",
        )
    )
    # Deliberately left unchecked: this is what a reviewer does when the package
    # does not contain what the claim would have to be checked against. It is the
    # difference between "passed" and "nobody looked", and it decides the outcome.
    chain.add_claim(
        Claim(
            "C3",
            "risk per position never exceeds 1% of equity",
            "spec",
            reproduction="",
        )
    )
    return chain


def main() -> int:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("specimen_statement.txt")
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        chain = build(root)
        st = issue_statement(
            chain,
            root,
            subject="SPECIMEN / synthetic demonstration package",
            scope=SCOPE,
            reviewer="Tomasz Wadowski - independent technical reviewer",
            now=datetime.now(timezone.utc),
        )
        assert verify_statement(st)

        body = BANNER + "\n" + render(st) + "\n\n" + """\
WHY THIS SPECIMEN ENDS IN CANNOT_VERIFY
--------------------------------------------------------------------------------
Two of the three claims were checked and supported. The third, C3, asserts a risk
cap - but the package supplies only a specification stating the cap, with nothing
against which the cap could be recomputed, and no command a third party could run.

A two-valued review has to put that somewhere, and it always ends up on the pass
side, because that is the side with no consequences. Here it does not: an
unchecked claim cannot produce ATTESTED, so the whole statement reads
CANNOT_VERIFY and names exactly which claim caused it.

That is the deliverable working as intended. If C3 had simply been counted as
fine, this document would say ATTESTED and would be worth nothing to whoever you
showed it to.

HOW TO CHECK THIS DOCUMENT HAS NOT BEEN EDITED
--------------------------------------------------------------------------------
The fingerprint above is a SHA-256 over the statement's own canonical form. Change
any character of any field - the decision, the scope, a digest, a finding - and it
stops matching. Verification is one call against the machine-readable statement
and needs nothing from me.
"""
        out.write_text(body, encoding="utf-8")

    print(body)
    print(f"\n[written to {out}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
